version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    tty: true
    ports:
      - 80:80
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    depends_on:
      - db
      - cache
    networks:
      - blog-network
  db:
    user: "1000"
    image: mysql:5.7
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - blog-network
  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
networks:
  blog-network:
    driver: bridge
